[package]
name = "schnorr_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-bigint-dig = "0.8.4"
rand = "0.8.5"
sha2 = "0.10.8"
